
CREATE TABLE Users(
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    Email VARCHAR (255) NOT NULL UNIQUE,
    Name VARCHAR (100),
    Phonenumber INT (100) NOT NULL UNIQUE,
    LastLogin TIMESTAMP DEFAULT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Credentials(
    CredentialID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT,
    PasswordHash VARCHAR (255) NOT NULL,
    FOREIGN KEY (UserID) REFERENCES Users(UserID) 
);