
CREATE TABLE Users (
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    Email VARCHAR(255) NOT NULL UNIQUE,
    Name VARCHAR (100),
    ProfilePicture VARCHAR(255),
    LastLogin TIMESTAMP DEFAULT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Credentials (
    CrendiatialID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT,
    PasswordHash VARCHAR(255) NOT NULL,
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
);
